import type { Component } from 'vue'
import {
  User, Users, TreePine, Globe, Hourglass, Badge, Shirt, Crown, Grab,
  Footprints as FootprintsIcon, CircleDot, LoaderCircle, ScrollText, UserCircle,
  Copy, Download, Upload, Plus, Minus, Menu, MoreHorizontal,
  Maximize2, Minimize2, MessageCircle, Brain, BookOpen, FileText, File,
  Terminal, Code2, Database, Bell, AlertTriangle, Info, CheckCircle,
  XCircle, HelpCircle, Filter, ArrowUpDown, Share2, Archive, Lock, Key,
  Mail, MessageSquare, Camera, Video, Monitor, Clock, Calendar, Flag,
  Bookmark, Heart, Send, Trash2, ZoomIn, Move, GripVertical, Pin, PinOff,
  Table, BarChart3, List, Grid3x3, Target, Shield, Swords, Sparkles,
  Zap, ImageIcon, Pencil, Eye, Folder, FolderOpen, ChevronDown,
  ChevronRight, ChevronUp, ChevronLeft, ArrowUp, ArrowDown, ArrowLeft,
  ArrowRight, X, Check, Home, Settings, Search, Link, Star, RefreshCw,
  Play, Pause, Keyboard, Tag, Palette, GripHorizontal, Undo2, Redo2,
  Printer, Brush, Unlock, Workflow, LayoutGrid, Puzzle, LayoutDashboard,
  GitBranch, Notebook, Music, MapPin, Map, CalendarDays, Package,
  Building2, Dna, Flame, Flower2, Landmark, Languages, ScrollText as ScrollTextIcon,
  Wand2, Lightbulb, Network, PenTool, Handshake, Repeat, Link2,
  Skull, LayoutList, ClipboardList, Coffee, Wrench, Loader, Coins,
  Moon, Hand, Type, Flower, Leaf, FlaskConical, Gem, Droplet, Construction, PawPrint,
  HardDrive, GitCompare, Activity, StickyNote, Paperclip, Glasses,
  ArrowLeftRight,
} from 'lucide-vue-next'

const LUCIDE_MAP: Record<string, Component> = {
  user: User,
  users: Users,
  tree: TreePine,
  web: Globe,
  hourglass: Hourglass,
  badge: Badge,
  clothing: Shirt,
  crown: Crown,
  gloves: Grab,
  pants: FootprintsIcon,
  boots: FootprintsIcon,
  ring: CircleDot,
  loading: LoaderCircle,
  scroll: ScrollText,
  person: UserCircle,
  copy: Copy,
  download: Download,
  upload: Upload,
  plus: Plus,
  minus: Minus,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  expand: Maximize2,
  collapse: Minimize2,
  chat: MessageCircle,
  brain: Brain,
  book: BookOpen,
  document: FileText,
  file: File,
  terminal: Terminal,
  code: Code2,
  database: Database,
  notification: Bell,
  bell: Bell,
  alert: AlertTriangle,
  info: Info,
  success: CheckCircle,
  error: XCircle,
  question: HelpCircle,
  help: HelpCircle,
  filter: Filter,
  sort: ArrowUpDown,
  share: Share2,
  export: Download,
  import: Upload,
  archive: Archive,
  lock: Lock,
  key: Key,
  people: Users,
  group: Users,
  mail: Mail,
  message: MessageSquare,
  camera: Camera,
  video: Video,
  monitor: Monitor,
  clock: Clock,
  calendar: Calendar,
  flag: Flag,
  bookmark: Bookmark,
  heart: Heart,
  send: Send,
  trash: Trash2,
  zoom: ZoomIn,
  move: Move,
  drag: GripVertical,
  pin: Pin,
  unpin: PinOff,
  table: Table,
  chart: BarChart3,
  list: List,
  grid: Grid3x3,
  target: Target,
  shield: Shield,
  sword: Swords,
  sparkles: Sparkles,
  zap: Zap,
  image: ImageIcon,
  pencil: Pencil,
  eye: Eye,
  folder: Folder,
  'folder-open': FolderOpen,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  x: X,
  check: Check,
  warning: AlertTriangle,
  home: Home,
  settings: Settings,
  search: Search,
  globe: Globe,
  link: Link,
  star: Star,
  refresh: RefreshCw,
  close: X,
  delete: Trash2,
  save: Download,
  edit: Pencil,
  play: Play,
  pause: Pause,
  keyboard: Keyboard,
  tag: Tag,
  palette: Palette,
  grip: GripHorizontal,
  undo: Undo2,
  redo: Redo2,
  print: Printer,
  brush: Brush,
  unlock: Unlock,
  'star-outline': Star,
  'file-select': Folder,
  workflow: Workflow,
  'tactical-board': LayoutGrid,
  'module-builder': Puzzle,
  dashboard: LayoutDashboard,
  'family-tree': GitBranch,
  notebook: Notebook,
  lightning: Zap,
  music: Music,
  location: MapPin,
  map: Map,
  event: CalendarDays,
  item: Package,
  profile: UserCircle,
  building: Building2,
  species: Dna,
  weapon: Swords,
  combat: Flame,
  plant: Flower2,
  culture: Landmark,
  language: Languages,
  manuscript: ScrollTextIcon,
  outline: LayoutList,
  magic: Wand2,
  concept: Lightbulb,
  mindmap: Network,
  inspiration: Lightbulb,
  organization: Building2,
  timeline: Clock,
  region: MapPin,
  character: User,
  graph: Share2,
  drawing: PenTool,
  race: Dna,
  apparel: Shirt,
  ally: Handshake,
  war: Swords,
  trade: Repeat,
  relation: Link2,
  'appearance-event': Sparkles,
  nametag: Tag,
  dragon: Flame,
  skull: Skull,
  'clipboard-list': ClipboardList,
  coffee: Coffee,
  wrench: Wrench,
  loader: Loader,
  coins: Coins,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  package: Package,
  moon: Moon,
  hand: Hand,
  text: Type,
  flower: Flower,
  leaf: Leaf,
  flask: FlaskConical,
  gem: Gem,
  water: Droplet,
  bridge: Construction,
  paw: PawPrint,
  'cat-storage': HardDrive,
  compare: GitCompare,
  devil: Flame,
  hero: Shield,
  love: Heart,
  motion: Activity,
  notepad: StickyNote,
  paperclip: Paperclip,
  puzzle: Puzzle,
  sunglasses: Glasses,
  wizard: Wand2,
  coin: Coins,
  handshake: Handshake,
  landmark: Landmark,
  'arrow-left-right': ArrowLeftRight,
}

export function resolveLucideIcon(name: string): Component | null {
  return LUCIDE_MAP[name] ?? null
}

export function hasLucideIcon(name: string): boolean {
  return name in LUCIDE_MAP
}
