// @worldsmith/entity-core - Entity engine core package
export * from './types'
export {
  WorldDatabase,
  db,
  isTauri,
  getStorageBackend,
  storage,
  entitySchemaRegistry,
  relationSchemaRegistry,
  fieldRegistry,
  pluginAPI,
  inverseRegistry,
  RelationTypes,
  RelationTypeLabels,
  InverseRelation,
  getRelationLabel,
  registerNodeType,
  getNodeTypeInfo,
  getNodeColor,
  getAllNodeTypes,
  registerEdgeType,
  getEdgeTypeInfo,
  getEdgeColor,
  getAllEdgeTypes,
  customFieldSerializer,
  entitySerializer,
  entityTypeSerializer,
  createModuleSerializer,
  relationSerializer,
  relationTypeSerializer,
  createViewSerializer,
  registerEventBus,
  getEventBus,
  registerValidationApi,
  getValidationApi,
  registerToastApi,
  getToastApi,
  registerConfirmApi,
  getConfirmApi,
  registerDialogApi,
  getDialogApi,
  registerSettingsApi,
  getSettingsApi,
} from './core'
export type {
  ModuleInstance,
  StorageBackend,
  RegisteredField,
  PluginAPIType,
  NodeTypeDefinition,
  WorkflowTemplateDefinition,
  ExternalNodeRegistry,
  RelationType,
  TypeInfo,
  EdgeTypeInfo,
  Serializer,
  ImportStrategy,
  ImportReportItem,
  EventBus,
  ValidationApi,
  ToastApi,
  ConfirmApi,
  DialogApi,
  SettingsApi,
} from './core'
export * from './stores'
export * from './composables'
export { entityCoreDescriptor } from './agent-descriptor'
