// @worldsmith/entity-core - Entity engine core package
export * from './types'
export {
  WorldDatabase,
  db,
  isTauri,
  getStorageBackend,
  storage,
  getProjectManager,
  migrateIfNeeded,
  entitySchemaRegistry,
  relationSchemaRegistry,
  fieldRegistry,
  pluginAPI,
  inverseRegistry,
  RelationTypes,
  RelationTypeLabels,
  InverseRelation,
  getRelationLabel,
  registerNodeType,
  getNodeTypeInfo,
  getNodeColor,
  getAllNodeTypes,
  registerEdgeType,
  getEdgeTypeInfo,
  getEdgeColor,
  getAllEdgeTypes,
  customFieldSerializer,
  entitySerializer,
  entityTypeSerializer,
  createModuleSerializer,
  relationSerializer,
  relationTypeSerializer,
  createViewSerializer,
  registerEventBus,
  getEventBus,
  registerValidationApi,
  getValidationApi,
  registerToastApi,
  getToastApi,
  registerConfirmApi,
  getConfirmApi,
  registerDialogApi,
  getDialogApi,
  registerSettingsApi,
  getSettingsApi,
  // Trait System V2
  traitRegistry,
  facetRegistry,
  entitySchemaRegistryV2,
  defineTrait,
  defineFacet,
  defineEntity,
  compileEntitySchema,
  // Relationship Registry V2
  relationshipRegistry,
  defineRelation,
  syncToLegacyRegistry,
  // AutoLink Engine
  semanticHintRegistry,
  autoLinkStrategyRegistry,
  registerDefaultStrategies,
  potentialLinkIndex,
  indexPotentialLinks,
  refreshLinksForTarget,
  inferSemanticHintFromKey,
  inferDirectTargetFromKey,
  userFieldMappingStore,
} from './core'
export type {
  ModuleInstance,
  ProjectSetting,
  ProjectInfo,
  StorageBackend,
  RegisteredField,
  PluginAPIType,
  NodeTypeDefinition,
  WorkflowTemplateDefinition,
  ExternalNodeRegistry,
  RelationType,
  TypeInfo,
  EdgeTypeInfo,
  Serializer,
  ImportStrategy,
  ImportReportItem,
  EventBus,
  ValidationApi,
  ToastApi,
  ConfirmApi,
  DialogApi,
  SettingsApi,
} from './core'
export type {
  PotentialLink,
  UserFieldMapping,
} from './core/AutoLinkEngine'
export * from './stores'
export * from './composables'
export { entityCoreDescriptor } from './agent-descriptor'
