// Stub for @worldsmith/tactical-engine when WASM is not built.
// The real module is generated by `wasm-pack build` into tactical-engine/pkg/.
// When WASM is available, Vite alias resolves to the real module instead.
export const TacticalEngine = undefined
