// Stub for @worldsmith/core when WASM is not built.
// The real module is generated by `wasm-pack build` into worldsmith-core/pkg/.
// When WASM is available, Vite alias resolves to the real module instead.
export const WorldSmithCore = undefined
