export {
  bridgePointInPolygon,
  bridgeSegmentsIntersect,
  bridgeSimplifyPoints,
  bridgeComputeMergedPolygon,
  bridgeChaikinSmooth,
  bridgeFindLinePolygonIntersections,
  bridgePolygonSplit,
  bridgePolygonAugment,
  bridgeMergePolygons,
  bridgeFindSharedEdges,
  localPointInPolygon,
  localSegmentsIntersect,
  localSimplifyPoints,
  localComputeMergedPolygon,
  localChaikinSmooth,
  localLineSegmentIntersection,
  localFindLinePolygonIntersections,
  localSplitPolygonAtIntersections,
  localBuildAugmentedPolygon,
  localMergePolygons,
  localPerpendicularDist,
  crossProduct,
} from './geometryBridge'
