export { useAutoCreateEntity } from './useAutoCreateEntity'
export { useSmartFieldLink } from './useSmartFieldLink'
export { useTypeMapping } from './useTypeMapping'
export { useBidirectional } from './useBidirectional'
export { deduplicateEdges, type MergedEdge } from './useEdgeDedup'
export { useStorageStats, type StorageStats } from './useStorageStats'
export { useOrphanCleanup, type OrphanFile } from './useOrphanCleanup'
export { useDataDiagnostics, type DanglingRelation, type DuplicateName, type DiagnosticResult } from './useDataDiagnostics'
export { useAutoCleanup } from './useAutoCleanup'
export { useSessionCleanup, type SessionCleanupState } from './useSessionCleanup'
export { useUndoRedo, isUndoing, setUndoHistoryProvider } from './useUndoRedo'
export { useEntityImage } from './useEntityImage'
export { useImageResolver, type ImagePersistedEvent, type UseImageResolverOptions, type UseImageResolverReturn } from './useImageResolver'
export { useCascadeDelete } from './useCascadeDelete'
export { useDirtyTracker } from './useDirtyTracker'
export { useTrash } from './useTrash'
export { useEntityTemplates } from './useEntityTemplates'
export { useAdvancedSearch, type SearchFilter } from './useAdvancedSearch'
export { useVersionSnapshot, type Snapshot } from './useVersionSnapshot'
export { useConsistencyChecker, type ConsistencyIssue } from './useConsistencyChecker'
